### ISSUE TITLE
API: add new table to keep track of current balance for accounts after each verification

### ISSUE THREAD

**Issue by winterrobert** [Senseworks-io/api#32]
Alex: Skriv spec här

**Comment by alexanderogren** [comment]
https://drive.google.com/drive/u/1/folders/1E-jOAr7xvAcqeHj52-sSX6YflFSdmgUr

Se "Förklaring ranking för ack saldo"

**Comment by MrSinclair** [comment]
Du har ark för allt! :-)

**Comment by MrSinclair** [comment]
Fixed with a column on transaction
